# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(section: "Overall Health")
Category.create(section: "Better Immunity")
Category.create(section: "Weight Loss")
Category.create(section: "Detox")
Category.create(section: "Reduce Inflammation")
Category.create(section: "Energy")
Category.create(section: "Digestive Health")
Category.create(section: "Heart Health")

Recipe.create(user_id: "1", category_id: "1", title: "Cancer Combatant", description: "Delicious citrus fruits combine with kefir and hydrating aloe to provide protection against free radical damage.", ingredient1: "2 kiwis", ingredient2: "1/2 cup pineapple", ingredient3: "1 cup low-fat kefir", ingredient4: "2 tablespoons aloe vera juice", directions: "Blend until all ingredients are thoroughly liquefied and combined", notes: "Taken from the 'I Love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "1", title: "Respiratory Relief", description: "Ployphenols in the berries help relieve respiratory distress by opening airways and protecting the body's cells against damage.", ingredient1: "1/2 cup blueberries", ingredient2: " 1/4 inch piece ginger, peeled", ingredient3: "1/2 cup blackberries", ingredient4: " 1 cup green tea, cooled", ingredient5: "2 tablespoons aloe vera juice", directions: "Blend until all ingredients are thoroughly combined", notes: "Taken from the 'I Love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "1", title: "Berry Blend for Bone Health", description: "Essential nutrients like vitamins B, A, C, and E, as well as calcium and magnesium, protect against the degradation of bone mass.", ingredient1: "1/2 cup raspberries", ingredient2: "1/2 cup blueberries", ingredient3: "1/2 cup pineapple", ingredient4: "1 cup nonfat Greek yogurt", directions: "Blend until all ingredients are thoroughly combined.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")
Recipe.create(user_id: "1", category_id: "1", title: "Sweet PMS Savior", description: "The Vitamin C, potassium, calcium, and protein in this smoothie help relieve the physical and mental symptoms of the dreaded premenstrual syndrome.", ingredient1: "1 cup strawberries", ingredient2: "1 banana, peeled and frozen", ingredient3: "1/2 cup pineapple", ingredient4: " 1/2 cup nonfat Greek yogurt", ingredient5: "2 tablespoons aloe vera juice", directions: "Blend until all ingredients are thoroughly combined.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")

Recipe.create(user_id: "1", category_id: "2", title: "Immunity Booster", description: "With antioxidant-packed ingredients that provide nutrients to dafeguard health and prvent disease, this super smoothie helps ward off colds, flus, and chronic disease.", ingredient1: "1/2 cup spinach", ingredient2: "1/2 large Granny Smith apple, cored", ingredient3: "1/2 large orange", ingredient4: "1/2 medium grapefruit, red or pink", ingredient5: "1 cup purified water, divided", directions: "Add first 4 ingredients and 1/2 cup of the water. Blend until all ingredients are thoroughly combined. Add remaining 1/2 cup of water as needed to achieve desired consistency.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")
Recipe.create(user_id: "1", category_id: "2", title: "Flu Fighter", description: "Savory blend of antioxidant-rich ingredients to help protect you against the flu and other viruses year-round.", ingredient1: "1/4 cup spinach", ingredient2: "1/2 teaspoon seaweed", ingredient3: "1/2 tomato", ingredient4: "1 clove garlic", ingredient5: "1 tablespoon red onion", ingredient6: "1 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")
Recipe.create(user_id: "1", category_id: "2", title: "Sore Throat Soother", description: "A combination of soothing honey and powerful antibacterial and antiviral ingredients help soothe a sore throat.", ingredient1: "1 cup cherries, pitted", ingredient2: "1/2 teaspoon ground organic cinnamon", ingredient3: "1/2 inch piece ginger, peeled", ingredient4: "1/2 tablespoon apple cider vinegar", ingredient5: "1 cup vanilla almond milk", ingredient6: "1 teaspoon all-natural honey", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")
Recipe.create(user_id: "1", category_id: "2", title: "Pomegranate for Prevention", description: "Packed with vitamins and powerful phytochemicals, this pomegranate smoothie is the perfect preventative measure.", ingredient1: "1/2 cup pomegranate jewels", ingredient2: "1/2 cup spinach", ingredient3: "1/2 banana, peeled and frozen", ingredient4: "1 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the ‘I love my NutriBullet Recipe Book’", public: "t")

Recipe.create(user_id: "1", category_id: "3", title: "Metabolism Maximizer", description: "This smoothie sparks a fire within the body for maximized fat burning potential.", ingredient1: "1/2 large Fuji apple, cored", ingredient2: "1 stalk celery, with leaves", ingredient3: "1/2 cucumber", ingredient4: "1/2 teaspoon spirulina", ingredient5: "1 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "3", title: "Five-Pound Fighter", description: "Fight those last five pounds with a hydrating, high fiber smoothie.", ingredient1: "1/2 cup spinach leaves", ingredient2: "1/2 large Fuji apple, cored", ingredient3: "1/2 cucumber", ingredient4: "1/2 stalk celery", ingredient5: "1/2 cup organic apple juice", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")

Recipe.create(user_id: "1", category_id: "4", title: "Spicy Pear Purifier", description: "This smoothie contains cleansing fiber and a rich supply of nutrients which support the systems that are responsibe for ridding the body of impurities.", ingredient1: "1/2 cup spinach", ingredient2: "1 large Bartlett pear, cored", ingredient3: "1/4 inch piece ginger, peeled", ingredient4: "1 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "4", title: "Hangover Healer", description: "A lingering 'less than healthy' feeling can result from overindulgence. This smoothie helps replenish and restore the body.", ingredient1: "1 medium cucumber", ingredient2: "1/2 medium red or pink grapefruit", ingredient3: "1/2 tangerine, peeled", ingredient4: "1 kiwi", ingredient5: "1/2 cup purified water", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")

Recipe.create(user_id: "1", category_id: "5", title: "Inflammation Immunity", description: "The cherries in this smoothie contain anti-inflammatory agents and antioxidants that help reduce inflammation throughout the body.", ingredient1: "1 cup cherries, pitted", ingredient2: "1 cup nonfat Greek yogurt", ingredient3: "1 tablespoon ground flax seed", ingredient4: "1/2 cup purified water", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "5", title: "Away with Arthritis", description: "Betalin-rich beets and fiber-rich bananas offer powerful protection against arthritis.", ingredient1: "1 red beet, greens removed, chopped", ingredient2: "1/2 banana, peeled and frozen", ingredient3: "1 kiwi", ingredient4: "1 tablespoon aloe vera juice", ingredient5: "1/2 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")

Recipe.create(user_id: "1", category_id: "6", title: "Rapid Raspberry Rev-Up", description: "Maximize energy levels with this super smoothie containing antioxidant-rich raspberries.", ingredient1: "1 cup raspberries", ingredient2: "1/4 inch piece ginger, peeled", ingredient3: "1 tablespoon aloe vera juice", ingredient4: "1 tablespoon coconut oil", ingredient5: "1 cup green tea, cooled", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "6", title: "Muscle Motivator", description: "Perfect pre-workout snack. Keeps blood sugar levels stable so you stay motivated and energized for hours.", ingredient1: "1/4 cup spinach", ingredient2: "1 kiwi", ingredient3: " 1/2 cup grapes", ingredient4: "1 small Fuji apple, cored", ingredient5: "1 cup organic apple juice", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")

Recipe.create(user_id: "1", category_id: "7", title: "Colitis-Calming-Carrot-Citrus-Apple", description: "This smoothie helps anyone with a troubled digestive system achive a better balance in the gut.", ingredient1: "1/2 Granny Smith apple, cored", ingredient2: "2 medium carrots, peeled and ends removed, chopped", ingredient3: "1 kiwi", ingredient4: "1/2 cup vanilla almond milk", ingredient5: "1/2 cup purified water", directions: "Blend until ingredients are thoroughly combined. Add water gradually while blending until desired consistency is achieved", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "7", title: "Constipation Cure", description: "Refreshing snack that will help get things moving, and help achieve regularity.", ingredient1: "2 kale leaves", ingredient2: "1 cup prunes, pitted", ingredient3: "1/2 Fuji apple, cored", ingredient4: "1 banana, peeled and frozen", ingredient5: "1 cup organic apple juice", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")

Recipe.create(user_id: "1", category_id: "8", title: "Cashew Milk", description: "Packed with heart healthy omega -3s, -6s, and -9s.", ingredient1: "1 cup raw cashews", ingredient2: "1 cup purified water", ingredient3: "1 tablespoon ground flax seed", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
Recipe.create(user_id: "1", category_id: "8", title: "Healthy Beets for Regular Beats", description: "Support heart health with essential minerals, cleansing fiber, and protective antioxidants.", ingredient1: "1 red beet, greens removed, chopped", ingredient2: " 1 banana, peeled and frozen", ingredient3: "1/2 cup spinach", ingredient4: "1 cup organic apple juice", directions: "Blend until ingredients are thoroughly combined.", notes: "Taken from the 'I love my NutriBullet Recipe Book'", public: "t")
